name: Windmill Docker Image Auto Release

on:
  schedule:
    # Set a schedule to check for changes, e.g., every day
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker image tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=true
          images: |
            name=ghcr.io/${{ github.repository_owner }}/windmill-playwright
          tags: |
            type=ref,event=pr
            type=raw,value=test,enable=true

      - name: Build and push server
        uses: docker/build-push-action@v5
        with:
          context: ./windmill
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
